name: CI/CD for BobApp

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      

jobs:
  # Backend build and test job
  build-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Restore dependencies from cache if available
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml')}}    
          restore-keys: |
            maven-

      # Build and test the backend using Maven
      - name: Build and Run Tests
        run: mvn clean verify dependency:copy-dependencies
        working-directory: ./back

      # Upload backend artifacts for Sonar analysis
      - name: Upload Backend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: |
            ./back/target/classes
            ./back/target/dependency
            ./back/target/site/jacoco/jacoco.xml

  # Frontend build and test job
  build-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # Restore dependencies from cache if available
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      # Install frontend dependencies 
      - name: Install Dependencies
        run: npm ci
        working-directory: ./front

      # Run frontend tests with coverage report
      - name: Run tests with coverage
        run: npm test -- --code-coverage --browsers ChromeHeadless --watch=false
        working-directory: ./front

      # Upload fronten artifacts for Sonar analysis
      - name: Upload Frontend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: ./front/coverage/bobapp/lcov.info 

  # SonarCloud code quality analysis
  sonar-code-quality:
    needs: [build-test-backend, build-test-frontend]  # Runs only if previous jobs are successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download backend artifacts
      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-artifacts
          path: ./artifacts

      # Download frontend artifacts
      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifacts
          path: ./artifacts    

      # Run SonarCloud analysis 
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Check SonarCloud Quality Gate status
      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt      

  # Docker build and push job
  docker-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Runs only on push to main branch
    needs: [sonar-code-quality]  # Runs only if SonarCloud analysis is successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Define environment variables for Docker images
      - name: Define Docker Image Tags
        run: |
          echo "BACK_IMAGE=${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest" >> $GITHUB_ENV
          echo "FRONT_IMAGE=${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest" >> $GITHUB_ENV

      # Build and push backend Docker image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t $BACK_IMAGE ./back
          docker push $BACK_IMAGE

      # Build and push frontend Docker image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t $FRONT_IMAGE ./front
          docker push $FRONT_IMAGE             



      
    








 